name: '[currency-cloud] Deploy to NuGet'
on:
  push:
    branches:
      - master
    paths:
      - source/**
  workflow_dispatch:
concurrency: '${{github.workflow}}-${{github.ref}}'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: src
    steps:
      # Environment setup
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Test solution
        run: dotnet test
      # Build
      - name: Build NuGet package
        run: >-
          dotnet pack ./Source/CurrencyCloud/CurrencyCloud.csproj
          "-p:Platform=Any CPU"
          -p:RepositoryUrl=https://github.com/ApprovalMax/approvalmax-product
          -p:Company=ApprovalMax
          -p:Authors=ApprovalMax
          --output ./build
      # Publish
      - name: Publish NuGet package
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/ApprovalMax/index.json \
            --name github \
            --username USERNAME \
            --password ${{secrets.GITHUB_TOKEN}} \
            --store-password-in-clear-text
          dotnet nuget push "build/*.nupkg" \
            --source https://nuget.pkg.github.com/ApprovalMax/index.json